apiVersion: apps/v1
kind: Deployment
metadata:
  name: study-room-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: study-room-frontend
  template:
    metadata:
      labels:
        app: study-room-frontend
    spec:
      containers:
      - name: study-room-frontend
        image: study-room-frontend:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: study-room-frontend-service
  namespace: default
spec:
  selector:
    app: study-room-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort
